name: Deploy

on:
  push:
    tags:
      - v*
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup .net core 2.2
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.402

      - name: Setup .net core 3.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100

      - name: .net SxS
        run: |
          rsync -a ${DOTNET_ROOT/3.0.100/2.2.402}/* $DOTNET_ROOT/

      - name: Setup Pulumi CLI
        run: |
          curl https://get.pulumi.com | bash
          echo "::add-path::$HOME/.pulumi/bin/"
        
      - name: Execute pulumi up
        working-directory: ./infra
        run: |
          pulumi stack select dev
          pulumi up
          echo "::set-env name=APP_NAME::$(pulumi stack output appName)"
          echo "::set-env name=FUNC_NAME::$(pulumi stack output funcName)"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - if: env.APP_NAME == '' || env.FUNC_NAME == ''
        run: exit 1

      - name: Restore and build projects
        run: |
          dotnet restore
          dotnet build --no-restore -c Release

      - name: Publish web app
        run: |
          dotnet publish --no-build -c Release -o publish/web src/App/App.csproj
          cd publish/web && zip -r ../web.zip .

      - name: Publish funcs app
        run: |
          dotnet publish --no-build -c Release -o publish/func src/Funcs/Funcs.csproj
          cd publish/funcs && zip -r ../funcs.zip .
        
      - name: 'Deploy web app'
        uses: azure/webapps-deploy@v1
        with: 
          app-name: ${{ env.APP_NAME }}
          package: './publish/web.zip' 
        
      - name: 'Deploy funcs app'
        uses: azure/functions-action@v1
        with: 
          app-name: ${{ env.FUNC_NAME }}
          package: './publish/funcs.zip'

      - name: Azure logout
        run: az logout