name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pulumi CLI
        run: |
          curl https://get.pulumi.com | bash
          PATH=$PATH:$HOME/.pulumi/bin
      - name: Setup .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Execute pulumi preview
        run: pulumi preview
        env:
          PULUMI_ROOT: ./infra
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
          COMMENT_ON_PR: 1