name: Pulumi preview

on:
  pull_request:
    paths:
      - 'infra/**'

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Pulumi CLI
        run: |
          curl https://get.pulumi.com | bash
          echo "::add-path::$HOME/.pulumi/bin/"

      - name: Setup .net core 3.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
        
      - name: Execute pulumi preview
        working-directory: ./infra
        run: |
          pulumi stack select dev
          pulumi preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Azure logout
        run: az logout