name: Deploy

on: push
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: xyz
        run: |
        cd src/App
        ls
        
      - run: ls

