name: Test SDK installs

on:
  - pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Setup .net core 2.2
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.402

      - name: Setup .net core 3.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100

      - name: move .net 2.2 to 3.0 folder
        run: |
          rsync -a ${DOTNET_ROOT/3.0.100/2.2.402}/* $DOTNET_ROOT/

      - name: List dncs/3.0.100/x64/sdk
        run: ls /opt/hostedtoolcache/dncs/3.0.100/x64/sdk

      - name: Run dotnet --info
        run: dotnet --info
