name: Test output variables

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        run: echo "::add-path::$HOME/.pulumi/bin/"

      - name: Read variable
        run: echo $PATH