name: Test SDK installs

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Setup .net core 2.2
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.402

      - name: Setup .net core 3.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100

      - name: List dncs
        run: ls /opt/hostedtoolcache/dncs/

      - name: List dncs/3.0.100/
        run: ls /opt/hostedtoolcache/dncs/3.0.100/

      - name: List dncs/3.0.100/x64
        run: ls /opt/hostedtoolcache/dncs/3.0.100/x64

      - name: List dncs/2.2.402/
        run: ls /opt/hostedtoolcache/dncs/2.2.402/

      - name: List dncs/2.2.402/x64
        run: ls /opt/hostedtoolcache/dncs/2.2.402/x64
