name: Test output variables

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        run: echo "::set-env name=MY_VAR::elo"

      - name: Read variable
        run: echo MY_VAR equals $MY_VAR