name: Test output variables

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        run: echo "::set-env name=MY_VAR::elo"

      - name: Read variable
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: $MY_VAR